### ISSUE TITLE
Black Pieces cant make it back row

### ISSUE THREAD

**Issue by jwilson780** [ModelTwelve/TCPChess#6]
With the newest branch, pretty much everything works but black pieces (other than pawns) can't make it to whites last row (not an error dealing with legal moves).  It seems to be with some problem in promotion, it keeps saying that a "pawn" can't move there.

**Comment by ModelTwelve** [comment]
The small amount of MOVE logic I did have setup wouldn't allow a PAWN 
to exist in the back row ... what I was doing was swapping the pawn out 
for the requested promotion piece and if I remember correctly that error 
was only thrown when there was no requested promotion piece provided in 
the MOVE action.

You're welcome to gut any of that logic and provide your own but I don't 
think it's actually legal for a PAWN to exist in the back row because it 
would have no move thereafter. Because of that I think you should error 
if no promotion piece is provided.

So ... if there's not an addition parameter being passed in the MOVE 
action then it's the clients fault and I'll fix it as soon as possible.

What say you?
